In [1]:
import numpy as np

data = np.array([1,2,3,4,5])
print(data)
print(type(data))
print(data.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [2]:
data = np.random.randn(2,3)
print(data)
print(data.shape)
print(data.dtype)

[[ 0.95170246 -1.65068799 -1.41136196]
 [ 0.01792897 -0.90958468  0.36861039]]
(2, 3)
float64


In [3]:
data1 = np.zeros(10)
print(data1)
print(data1.dtype)

data2 = np.zeros((2, 3))
print(data2)

data3 = np.zeros((2, 3), dtype=np.int32)
print(data3)
print(data3.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
int32


In [4]:
data1 = np.ones(8)
print(data1)
print(data1.dtype)

data2 = np.ones((3, 4), dtype=np.int32)
print(data2)
print(data2.dtype)

[1. 1. 1. 1. 1. 1. 1. 1.]
float64
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [5]:
data = np.arange(10, 121, 10)
print(data)
print(data[2])
print(data[5:8])
print(data.dtype)

data[7:10] = 800
print(data)

data2 = data.reshape(2, 6)
print(data2)
print(data2.dtype)

[ 10  20  30  40  50  60  70  80  90 100 110 120]
30
[60 70 80]
int32
[ 10  20  30  40  50  60  70 800 800 800 110 120]
[[ 10  20  30  40  50  60]
 [ 70 800 800 800 110 120]]
int32


In [6]:
data = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

print(data)
print(data[2][3])
print(data[0][1:])
print(data[0])
print(data[[1,2]])
print()

data[1] = 100
print(data)
print()

data[:] = 200
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
14
[2 3 4 5]
[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [ 11  12  13  14  15]]

[[200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]]


In [7]:
a = np.array([
    [10,7,-8,-2],
    [-2,2,8,3],
    [6,-8,-5,3]
])

b = a * 2
print(b)
print()

c = a * a
print(c)
print()

print(a > b)

[[ 20  14 -16  -4]
 [ -4   4  16   6]
 [ 12 -16 -10   6]]

[[100  49  64   4]
 [  4   4  64   9]
 [ 36  64  25   9]]

[[False False  True  True]
 [ True False False False]
 [False  True  True False]]


In [8]:
data = np.array([
    [80, 78, 90, 93],
    [65, 87, 88, 75],
    [98, 100, 68, 80]
])

print(data.sum())
print(data.mean())
print(data.max())
print(data.min())
print()

print(data.max(axis=0))
print(data.max(axis=1))
print()

index1 = np.argmax(data, axis=0)
index2 = np.argmin(data, axis=1)
print(index1, index2)

1002
83.5
100
65

[ 98 100  90  93]
[ 93  88 100]

[2 2 0 0] [1 0 2]
